"""It's a simple program to check whether the user is entering a valid
details and checking the email id by sending an OTP """

import smtplib  # library used to send OTP
import random as r  # library used to generate OTP


class login:

    def user_details(self):  # checking whether the user had entered valid details

        name = input("Name : ")
        age = input("Age : ")
        password = input("password should consist at least one special character \nPassword : ")
        password1 = input("Enter your password again : ")
        spec = ['!', '@', '#', '$', '%', '^', '&', '*', '~']

        if name.isalpha():
            if age.isdigit():
                for i in password:
                    if i in spec and password == password1:
                        print("Valid Details")
                        obj.email()  # Generating emails once the user details are valid.
                        break
                    else:
                        print("Password is not valid or enter the correct password")
                        break
            else:
                print("Invalid age")
        else:
            print("Invalid User name")

    def email(self):  # Generating OTP and sending the mail

        try:
            otp = ""
            for i in range(5):
                otp += str(r.randint(1, 9))
            message = otp
            E_mail = input("E-mail : ")
            print("Sending otp.....!")
            sender_email = "vicky6info@gmail.com"  # enter Your email Id
            rec_mail = E_mail
            password = "qltv aolt udbw akhv"  # enter the password generated by your google account
            server = smtplib.SMTP('smtp.gmail.com', 587)
            server.starttls()
            server.login(sender_email, password)
            server.sendmail(sender_email, rec_mail, message)
            print("OTP has been sent successfully")
            Login_otp = input("Enter the OTP : ")
            if message == Login_otp:
                print("Email verified\n!!! Login Created Successful !!!")
            else:
                print("The entered otp is in-correct")
        except:
            print("You have entered a wrong email address please check")


obj = login()
obj.user_details()  # calling my main function
